#!/usr/bin/env bash
set -euo pipefail

# 공식 Langfuse repository를 받아 self-host Docker Compose 실습 디렉터리를 준비한다.
#
# 중요한 점:
# - Langfuse self-host compose는 Langfuse 버전에 따라 바뀔 수 있다.
# - 그래서 이 스터디 repo에 compose 파일을 복사해 고정하지 않고,
#   공식 repo의 docker-compose.yml을 기준으로 실습한다.
# - 폐쇄망에서는 인터넷이 되는 환경에서 이 script를 먼저 실행하거나,
#   공식 repo를 tar로 묶어 내부망으로 반입한다.

SELF_HOST_DIR="${SELF_HOST_DIR:-self-host/langfuse-official}"
LANGFUSE_REPO="${LANGFUSE_REPO:-https://github.com/langfuse/langfuse.git}"
LANGFUSE_VERSION="${LANGFUSE_VERSION:-main}"
ENV_FILE="${SELF_HOST_DIR}/.env"

random_base64() {
  # Langfuse secret, auth secret처럼 일반 secret 값에 쓸 base64 random 문자열을 만든다.
  # openssl이 있으면 openssl을 쓰고, 없으면 Python secrets로 fallback한다.
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32
  else
    python3 - <<'PY'
import base64
import secrets
print(base64.b64encode(secrets.token_bytes(32)).decode("ascii"))
PY
  fi
}

random_hex_32_bytes() {
  # 공식 compose의 ENCRYPTION_KEY는 `openssl rand -hex 32` 형태를 권장한다.
  # 그래서 이 값만 base64가 아니라 64자리 hex 문자열로 만든다.
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
  fi
}

random_url_safe_password() {
  # DATABASE_URL, Redis auth, MinIO secret처럼 URL이나 command line에 들어갈 수 있는
  # 값은 `/`, `+`, `=`가 없는 문자열이 덜 헷갈린다.
  # base64 random 값을 만든 뒤 alphanumeric 문자만 남겨 32자로 줄인다.
  local value
  value="$(random_base64 | tr -dc 'A-Za-z0-9' | head -c 32)"
  if [[ -z "${value}" ]]; then
    value="$(date +%s%N | sha256sum | head -c 32)"
  fi
  printf '%s\n' "${value}"
}

mkdir -p "$(dirname "${SELF_HOST_DIR}")"

if [[ -d "${SELF_HOST_DIR}/.git" ]]; then
  echo "Langfuse repo already exists: ${SELF_HOST_DIR}"
else
  echo "Cloning Langfuse official repo..."
  git clone --depth 1 --branch "${LANGFUSE_VERSION}" "${LANGFUSE_REPO}" "${SELF_HOST_DIR}"
fi

if [[ ! -f "${SELF_HOST_DIR}/docker-compose.yml" ]]; then
  echo "Missing ${SELF_HOST_DIR}/docker-compose.yml"
  echo "The official repository layout may have changed. Check Langfuse self-host docs."
  exit 1
fi

if [[ -f "${ENV_FILE}" && "${SELF_HOST_ENV_OVERWRITE:-false}" != "true" ]]; then
  echo "Self-host .env already exists: ${ENV_FILE}"
  echo "Keep existing secrets. To regenerate, run:"
  echo "  SELF_HOST_ENV_OVERWRITE=true bash scripts/06_prepare_self_host_official.sh"
else
  if [[ -f "${ENV_FILE}" ]]; then
    cp "${ENV_FILE}" "${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  fi

  POSTGRES_PASSWORD="$(random_url_safe_password)"
  CLICKHOUSE_PASSWORD="$(random_url_safe_password)"
  REDIS_AUTH="$(random_url_safe_password)"
  MINIO_ROOT_PASSWORD="$(random_url_safe_password)"

  cat > "${ENV_FILE}" <<EOF
# Generated by model-serving study script.
# Do not commit this file. It contains local self-host secrets.

NEXTAUTH_URL=http://localhost:3000

# Langfuse application secrets.
SALT=$(random_base64)
ENCRYPTION_KEY=$(random_hex_32_bytes)
NEXTAUTH_SECRET=$(random_base64)

# Postgres.
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=postgres
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres

# ClickHouse.
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

# Redis/Valkey.
REDIS_AUTH=${REDIS_AUTH}

# MinIO / S3-compatible object storage.
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=minio
LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}

# Local study login convention.
# If the UI asks you to create the first account manually, use:
#   user/name: admin
#   password: admin123
# If the UI requires an email format, use:
#   email: admin@example.local
LANGFUSE_INIT_USER_EMAIL=admin@example.local
LANGFUSE_INIT_USER_NAME=admin
LANGFUSE_INIT_USER_PASSWORD=admin123
EOF

  chmod 600 "${ENV_FILE}"
  echo "Generated self-host .env with random secrets: ${ENV_FILE}"
fi

cat <<EOF
Prepared: ${SELF_HOST_DIR}

Next:
  cd ${SELF_HOST_DIR}
  grep -n "CHANGEME" docker-compose.yml
  sed -n '1,80p' .env

이 script는 공식 docker-compose.yml을 직접 수정하지 않고 같은 디렉터리의 .env로 값을 override한다.
SALT, NEXTAUTH_SECRET 등은 base64 random 값으로 만들고,
ENCRYPTION_KEY는 공식 권장 형식에 맞춰 64자리 hex 값으로 만든다.

UI에서 첫 계정을 직접 만들어야 하면 학습용으로 아래 값을 사용한다.
  user/name: admin
  email: admin@example.local
  password: admin123
EOF
